// Copyright 2026 agent-media contributors. Apache-2.0 license.

/**
 * `agent-media completions <shell>` command.
 *
 * Generates shell completion scripts for bash, zsh, and fish.
 * Users pipe the output into their shell's configuration to enable
 * tab-completion of commands, options, and arguments.
 *
 * Usage:
 *   agent-media completions bash >> ~/.bashrc
 *   agent-media completions zsh  >> ~/.zshrc
 *   agent-media completions fish > ~/.config/fish/completions/agent-media.fish
 */

import type { Command } from 'commander';
import { CLIError, handleError } from '../lib/errors.js';

/** All registered command names (used in completion scripts). */
const COMMANDS = [
  'actor',
  'alias',
  'apikey',
  'cancel',
  'completions',
  'config',
  'credits',
  'debug',
  'delete',
  'doctor',
  'download',
  'inspect',
  'list',
  'login',
  'logout',
  'persona',
  'plan',
  'profile',
  'status',
  'subscribe',
  'subtitle',
  'ugc',
  'update',
  'usage',
  'version',
  'whoami',
];

/** Global option flags available on all commands. */
const GLOBAL_FLAGS = [
  '--json',
  '--quiet',
  '--no-color',
  '--verbose',
  '--profile',
  '--help',
  '--version',
];

/**
 * Generate a Bash completion script.
 */
function generateBash(): string {
  const cmds = COMMANDS.join(' ');
  const flags = GLOBAL_FLAGS.join(' ');

  return `# agent-media bash completion
# Generated by: agent-media completions bash
# Add to ~/.bashrc or ~/.bash_profile:
#   eval "$(agent-media completions bash)"

_agent_media_completions() {
    local cur prev commands global_flags
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    commands="${cmds}"
    global_flags="${flags}"

    # Complete subcommands when at position 1
    if [[ \${COMP_CWORD} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
        return 0
    fi

    # Complete global flags
    if [[ "\${cur}" == -* ]]; then
        COMPREPLY=( $(compgen -W "\${global_flags}" -- "\${cur}") )
        return 0
    fi

    # Command-specific completions
    case "\${COMP_WORDS[1]}" in
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
            ;;
        config)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "get set list reset export import" -- "\${cur}") )
            elif [[ \${COMP_CWORD} -eq 3 && ("\${prev}" == "get" || "\${prev}" == "set") ]]; then
                COMPREPLY=( $(compgen -W "api_url output_format default_model auto_open_browser download_dir" -- "\${cur}") )
            fi
            ;;
        credits)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "estimate history topup" -- "\${cur}") )
            fi
            ;;
        ugc)
            # UGC has many options but no positional subcommands to complete
            ;;
        actor)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "list preview" -- "\${cur}") )
            fi
            ;;
        persona)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "list create delete" -- "\${cur}") )
            fi
            ;;
        apikey)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "list create revoke" -- "\${cur}") )
            fi
            ;;
        profile)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "list use delete export" -- "\${cur}") )
            fi
            ;;
        alias)
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "set remove list" -- "\${cur}") )
            fi
            ;;
    esac

    return 0
}

complete -F _agent_media_completions agent-media
`;
}

/**
 * Generate a Zsh completion script.
 */
function generateZsh(): string {
  const cmdLines = COMMANDS.map((cmd) => `    '${cmd}:${cmd} command'`).join(' \\\n');

  return `#compdef agent-media

# agent-media zsh completion
# Generated by: agent-media completions zsh
# Add to ~/.zshrc:
#   eval "$(agent-media completions zsh)"
# Or save to a file in your $fpath:
#   agent-media completions zsh > ~/.zsh/completions/_agent-media

_agent-media() {
    local -a commands
    commands=(
${cmdLines}
    )

    local -a global_flags
    global_flags=(
        '--json[Output as JSON]'
        '--quiet[Minimal output]'
        '--no-color[Disable colored output]'
        '--verbose[Show debug output]'
        '--profile[Use a specific credential profile]:profile name'
        '--help[Show help]'
        '--version[Show version]'
    )

    _arguments -C \\
        '1:command:->command' \\
        '*::arg:->args' \\
        \${global_flags}

    case "$state" in
        command)
            _describe -t commands 'agent-media command' commands
            ;;
        args)
            case "$words[1]" in
                completions)
                    _values 'shell' bash zsh fish
                    ;;
                config)
                    local -a config_subcmds
                    config_subcmds=(get set list reset export import)
                    if (( CURRENT == 2 )); then
                        _describe -t subcommands 'config subcommand' config_subcmds
                    elif (( CURRENT == 3 )) && [[ "$words[2]" == (get|set) ]]; then
                        local -a config_keys
                        config_keys=(api_url output_format default_model auto_open_browser download_dir)
                        _describe -t keys 'config key' config_keys
                    fi
                    ;;
                credits)
                    local -a credits_subcmds
                    credits_subcmds=(estimate history topup)
                    _describe -t subcommands 'credits subcommand' credits_subcmds
                    ;;
                ugc)
                    # UGC has many options but no positional subcommands
                    ;;
                actor)
                    local -a actor_subcmds
                    actor_subcmds=(list preview)
                    _describe -t subcommands 'actor subcommand' actor_subcmds
                    ;;
                persona)
                    local -a persona_subcmds
                    persona_subcmds=(list create delete)
                    _describe -t subcommands 'persona subcommand' persona_subcmds
                    ;;
                apikey)
                    local -a apikey_subcmds
                    apikey_subcmds=(list create revoke)
                    _describe -t subcommands 'apikey subcommand' apikey_subcmds
                    ;;
                profile)
                    local -a profile_subcmds
                    profile_subcmds=(list use delete export)
                    _describe -t subcommands 'profile subcommand' profile_subcmds
                    ;;
                alias)
                    local -a alias_subcmds
                    alias_subcmds=(set remove list)
                    _describe -t subcommands 'alias subcommand' alias_subcmds
                    ;;
                download|status|inspect|cancel|delete)
                    _message 'job ID'
                    ;;
            esac
            ;;
    esac
}

_agent-media "$@"
`;
}

/**
 * Generate a Fish completion script.
 */
function generateFish(): string {
  const cmdCompletions = COMMANDS.map(
    (cmd) => `complete -c agent-media -n "__fish_use_subcommand" -a "${cmd}" -d "${cmd} command"`,
  ).join('\n');

  return `# agent-media fish completion
# Generated by: agent-media completions fish
# Save to: ~/.config/fish/completions/agent-media.fish

# Disable file completions by default
complete -c agent-media -f

# Global flags
complete -c agent-media -l json -d "Output as JSON"
complete -c agent-media -l quiet -d "Minimal output"
complete -c agent-media -l no-color -d "Disable colored output"
complete -c agent-media -l verbose -d "Show debug output"
complete -c agent-media -l profile -d "Use a specific credential profile" -x
complete -c agent-media -l help -d "Show help"
complete -c agent-media -l version -d "Show version"

# Subcommands
${cmdCompletions}

# completions subcommand
complete -c agent-media -n "__fish_seen_subcommand_from completions" -a "bash zsh fish" -d "Shell type"

# config subcommand
complete -c agent-media -n "__fish_seen_subcommand_from config" -a "get set list reset export import" -d "Config action"

# credits subcommand
complete -c agent-media -n "__fish_seen_subcommand_from credits" -a "estimate history topup" -d "Credits action"

# ugc subcommand (no positional completions, uses flags)

# actor subcommand
complete -c agent-media -n "__fish_seen_subcommand_from actor" -a "list preview" -d "Actor action"

# persona subcommand
complete -c agent-media -n "__fish_seen_subcommand_from persona" -a "list create delete" -d "Persona action"

# apikey subcommand
complete -c agent-media -n "__fish_seen_subcommand_from apikey" -a "list create revoke" -d "API key action"

# profile subcommand
complete -c agent-media -n "__fish_seen_subcommand_from profile" -a "list use delete export" -d "Profile action"

# alias subcommand
complete -c agent-media -n "__fish_seen_subcommand_from alias" -a "set remove list" -d "Alias action"
`;
}

export function registerCompletionsCommand(program: Command): void {
  program
    .command('completions <shell>')
    .description(
      'Generate shell completion scripts\n\n' +
      'Usage:\n' +
      '  agent-media completions bash >> ~/.bashrc\n' +
      '  agent-media completions zsh  >> ~/.zshrc\n' +
      '  agent-media completions fish > ~/.config/fish/completions/agent-media.fish',
    )
    .action((shell: string) => {
      try {
        const shellLower = shell.toLowerCase();

        switch (shellLower) {
          case 'bash':
            process.stdout.write(generateBash());
            break;

          case 'zsh':
            process.stdout.write(generateZsh());
            break;

          case 'fish':
            process.stdout.write(generateFish());
            break;

          default:
            throw new CLIError(`Unsupported shell: "${shell}"`, {
              code: 'UNSUPPORTED_SHELL',
              suggestion: 'Supported shells: bash, zsh, fish',
            });
        }
      } catch (error: unknown) {
        handleError(error);
      }
    });
}
