// AUTO-GENERATED by packages/schema/scripts/generate-edge-schema.ts
// DO NOT EDIT. Source of truth: packages/schema/src/video.ts
// Re-generate: pnpm --filter @agent-media/schema generate:edge-schema

export const DURATIONS = [5, 10, 15] as const;
export const TONES = ["energetic", "calm", "confident", "dramatic"] as const;
export const MUSIC_GENRES = ["chill", "energetic", "corporate", "dramatic", "upbeat"] as const;
export const SUBTITLE_STYLES = [
  "hormozi",
  "minimal",
  "bold",
  "karaoke",
  "clean",
  "tiktok",
  "neon",
  "fire",
  "glow",
  "pop",
  "aesthetic",
  "impact",
  "pastel",
  "electric",
  "boxed",
  "gradient",
  "spotlight",
] as const;
export const ASPECT_RATIOS = ["9:16", "16:9", "1:1"] as const;
export const SCENE_TYPES = ["talking_head", "broll"] as const;
export const TEMPLATES = [
  "monologue",
  "testimonial",
  "product-review",
  "problem-solution",
  "saas-review",
  "before-after",
  "listicle",
  "product-demo",
] as const;
export const VOICES = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"] as const;
export const TTS_PROVIDERS = ["openai", "elevenlabs", "hume"] as const;
export const REVIEW_ANGLES = ["honest", "enthusiastic", "roast", "tutorial", "comparison"] as const;
export const PIP_POSITIONS = ["bottom-center", "bottom-left", "bottom-right"] as const;
export const PIP_SIZES = ["small", "medium", "large"] as const;
export const PIP_ANIMATIONS = ["slide-up", "slide-left", "slide-right", "fade", "scale"] as const;
export const PIP_FRAME_STYLES = ["none", "rounded", "shadow"] as const;
export const COMPOSITION_MODES = ["pip"] as const;
export const BROLL_MODELS = ["kling3", "hailuo2", "wan21"] as const;

export const CREDITS_PER_SECOND = 30;
export const SCRIPT_GENERATION_CREDIT_SURCHARGE = 5;
