export type Gender = 'female' | 'male';
export type AgeRange = '18–25' | '26–35' | '36–50' | '51+';
export type ActorType = 'Young Adult' | 'Professional' | 'Mom' | 'Elder' | 'Casual';

export interface ActorMeta {
  id: number;
  name: string;
  age: number;
  gender: Gender;
  nationality: string;
  style: string;
  type: ActorType;
}

export function ageRange(age: number): AgeRange {
  if (age <= 25) return '18–25';
  if (age <= 35) return '26–35';
  if (age <= 50) return '36–50';
  return '51+';
}

// [name, age, gender, nationality, style, type]
type Row = [string, number, Gender, string, string, ActorType];

const RAW: Row[] = [
  ['Emma', 28, 'female', 'European', 'Warm, approachable, gentle creative spirit', 'Young Adult'],
  ['Carlos', 50, 'male', 'Latino', 'Serious, contemplative, mature presence', 'Professional'],
  ['Wei', 35, 'male', 'Southeast Asian', 'Friendly approachable casual everyday vibe', 'Casual'],
  ['Madison', 42, 'female', 'Caucasian', 'Calm, approachable, thoughtful presence', 'Professional'],
  ['Marcus', 58, 'male', 'African', 'Wise, distinguished, thoughtful presence', 'Elder'],
  ['Mei', 26, 'female', 'East Asian', 'Elegant, poised, culturally graceful presence', 'Young Adult'],
  ['Sophie', 28, 'female', 'European', 'Warm, approachable, and professionally poised', 'Professional'],
  ['Jin', 28, 'male', 'Southeast Asian', 'Cheerful, vibrant, expressive and friendly', 'Young Adult'],
  ['Devon', 35, 'male', 'African American', 'Confident, thoughtful, culturally aware presence', 'Professional'],
  ['Jamal', 24, 'male', 'African', 'Cheerful, friendly, warm, genuine smile', 'Young Adult'],
  ['Layla', 26, 'female', 'Middle Eastern', 'Thoughtful, elegant, and naturally radiant', 'Young Adult'],
  ['Kwame', 28, 'male', 'African', 'Confident, poised, thoughtful presence', 'Young Adult'],
  ['Sofia', 32, 'female', 'Latina', 'joyful, energetic, tropical vacation vibes', 'Mom'],
  ['Hiro', 32, 'male', 'East Asian', 'Thoughtful, composed, introspective presence', 'Young Adult'],
  ['Claire', 26, 'female', 'European', 'Warm, cheerful, approachable, and genuine', 'Young Adult'],
  ['Nour', 28, 'female', 'Middle Eastern', 'Confident, elegant, and approachable', 'Professional'],
  ['Ahmed', 28, 'male', 'Middle Eastern', 'Thoughtful, artistic, introspective', 'Young Adult'],
  ['Kofi', 38, 'male', 'African American', 'Confident, approachable, vibrant energy', 'Professional'],
  ['Anna', 26, 'female', 'Northern European', 'Warm, creative, approachable, and genuine', 'Young Adult'],
  ['Tobias', 28, 'male', 'African', 'Calm, introspective, and composed presence', 'Young Adult'],
  ['Lisa', 42, 'female', 'European', 'Warm, approachable, confident professional', 'Mom'],
  ['Seun', 35, 'male', 'African', 'Warm, confident, approachable presence', 'Professional'],
  ['Julia', 25, 'female', 'European', 'Warm, friendly, and approachable presence', 'Young Adult'],
  ['Ashley', 42, 'female', 'Caucasian', 'Confident, polished, intelligent professional presence', 'Professional'],
  ['Omar', 26, 'male', 'Middle Eastern', 'Calm, approachable, contemplative presence', 'Young Adult'],
  ['Kenji', 28, 'male', 'Southeast Asian', 'Friendly approachable casual confidence', 'Young Adult'],
  ['Jessica', 32, 'female', 'Caucasian', 'Approachable, calm, understated elegance', 'Mom'],
  ['Eli', 28, 'male', 'African', 'Joyful, charismatic, culturally vibrant', 'Young Adult'],
  ['Valeria', 38, 'female', 'Latin American', 'Natural, serene, grounded forest dweller', 'Mom'],
  ['Samuel', 26, 'male', 'African American', 'Confident, modern, laid-back creative vibe', 'Young Adult'],
  ['Isabella', 28, 'female', 'Latin American', 'Warm, expressive, friendly, approachable', 'Young Adult'],
  ['Darius', 28, 'male', 'African American', 'Bold, confident, creative street vibes', 'Young Adult'],
  ['Camila', 45, 'female', 'Latin American', 'Warm, approachable, genuine, thoughtful presence', 'Mom'],
  ['Jordan', 35, 'male', 'African', 'Warm, charismatic, tropical vacation energy', 'Young Adult'],
  ['Sarah', 28, 'female', 'European', 'Warm, approachable, naturally radiant', 'Mom'],
  ['Luca', 38, 'male', 'European', 'Thoughtful, introspective, intellectually grounded', 'Professional'],
  ['Gabriela', 26, 'female', 'Latin American', 'Confident, approachable, and naturally elegant', 'Young Adult'],
  ['Arjun', 22, 'male', 'South Asian', 'Friendly, casual, approachable market vendor', 'Young Adult'],
  ['Laura', 28, 'female', 'Northern European', 'Calm, thoughtful, approachable presence', 'Young Adult'],
  ['Olumide', 28, 'male', 'African American', 'Friendly, approachable, casual confidence', 'Young Adult'],
  ['Lin', 35, 'female', 'East Asian', 'Warm, approachable, genuine and calm', 'Mom'],
  ['Tyler', 32, 'male', 'Caucasian', 'friendly approachable laid-back casual', 'Young Adult'],
  ['Destiny', 28, 'female', 'African', 'Confident, natural, minimalist aesthetic', 'Young Adult'],
  ['Kai', 48, 'male', 'Mediterranean', 'Sophisticated, mature, contemplative presence', 'Professional'],
  ['Amara', 22, 'female', 'African American', 'Artistic, creative, introspective vibe', 'Young Adult'],
  ['Ali', 35, 'male', 'Middle Eastern', 'Confident, well-groomed, approachable professional', 'Professional'],
  ['Nia', 28, 'female', 'African American', 'Vibrant, confident, warm and approachable', 'Young Adult'],
  ['Marco', 42, 'male', 'European', 'Thoughtful and approachable with quiet confidence', 'Professional'],
  ['Naomi', 24, 'female', 'Mixed ethnicity', 'Energetic, friendly, cheerful and vibrant', 'Young Adult'],
  ['Takeshi', 45, 'male', 'East Asian', 'Serious, contemplative, understated confidence', 'Professional'],
  ['Simone', 26, 'female', 'African American', 'Confident, vibrant, culturally proud presence', 'Young Adult'],
  ['Hassan', 28, 'male', 'Mediterranean or Middle Eastern', 'Casual confident approachable creative vibe', 'Young Adult'],
  ['Fernanda', 28, 'female', 'Latina', 'Thoughtful, approachable, naturalistic presence', 'Young Adult'],
  ['Daiki', 58, 'male', 'East Asian', 'Calm, thoughtful, dignified presence', 'Elder'],
  ['Yuki', 22, 'female', 'East Asian', 'Modern, trendy, confident creative vibe', 'Young Adult'],
  ['Emeka', 45, 'male', 'African American', 'Thoughtful, calm, and introspective presence', 'Professional'],
  ['Chloe', 28, 'female', 'European', 'Warm, friendly, approachable and genuine', 'Young Adult'],
  ['Ade', 32, 'male', 'African American', 'Confident, approachable, modern professional', 'Professional'],
  ['Hana', 25, 'female', 'East Asian', 'Approachable, natural, gentle, and serene', 'Young Adult'],
  ['Khalid', 32, 'male', 'Middle Eastern', 'Thoughtful, introspective, calm presence', 'Young Adult'],
  ['Daniela', 26, 'female', 'Latina', 'Warm, approachable, joyful and vibrant', 'Young Adult'],
  ['Austin', 28, 'male', 'Caucasian', 'Friendly, approachable, casual and relaxed', 'Young Adult'],
  ['Aaliyah', 28, 'female', 'African American', 'Confident, poised, thoughtful presence', 'Professional'],
  ['Jun', 32, 'male', 'Southeast Asian', 'Calm, contemplative, and spiritually grounded', 'Young Adult'],
  ['Natalia', 24, 'female', 'Latina', 'Natural, confident, effortlessly beautiful aesthetic', 'Young Adult'],
  ['Brandon', 52, 'male', 'Caucasian', 'Accomplished professional with understated confidence', 'Professional'],
  ['Fatou', 28, 'female', 'African American', 'Warm, approachable, intelligent, and confident', 'Professional'],
  ['Julian', 28, 'male', 'European', 'Modern, thoughtful, creative urbanite', 'Young Adult'],
  ['Sakura', 25, 'female', 'Southeast Asian', 'Warm, approachable, naturally confident', 'Young Adult'],
  ['Ravi', 42, 'male', 'Mediterranean', 'Sophisticated, confident, artistic presence', 'Professional'],
  ['Imani', 26, 'female', 'African American', 'Joyful, warm, and genuinely friendly presence', 'Young Adult'],
  ['Tariq', 48, 'male', 'Middle Eastern', 'Thoughtful, dignified, introspective presence', 'Professional'],
  ['Valentina', 26, 'female', 'Latina', 'Creative, warm, and approachable personality', 'Young Adult'],
  ['Felix', 32, 'male', 'European', 'Casual, approachable, laid-back vibe', 'Young Adult'],
  ['Aiko', 25, 'female', 'Southeast Asian', 'Friendly, approachable, genuine presence', 'Young Adult'],
  ['Dylan', 52, 'male', 'Caucasian', 'Thoughtful, seasoned, approachable professional', 'Professional'],
  ['Kemi', 26, 'female', 'African American', 'Warm, vibrant, joyful, and approachable', 'Young Adult'],
  ['Min-Jun', 24, 'male', 'East Asian', 'Thoughtful, introspective, modern casual', 'Young Adult'],
  ['Taylor', 28, 'female', 'Caucasian', 'Warm, approachable, creative home-focused', 'Young Adult'],
  ['Dele', 24, 'male', 'African American', 'Warm, friendly, approachable and genuine', 'Young Adult'],
  ['Sara', 32, 'female', 'Middle Eastern', 'Polished, confident, modern professional', 'Professional'],
  ['Youssef', 28, 'male', 'Middle Eastern', 'Confident, modern, approachable creative', 'Young Adult'],
  ['Yuna', 24, 'female', 'East Asian', 'Excited, energetic, friendly content creator', 'Young Adult'],
  ['Femi', 62, 'male', 'African American', 'Thoughtful, dignified, seasoned wisdom', 'Elder'],
  ['Mariana', 32, 'female', 'Latina', 'Warm, approachable, and genuinely friendly', 'Mom'],
  ['Ethan', 35, 'male', 'Caucasian', 'Relaxed coastal surfer beach vibe', 'Casual'],
  ['Precious', 28, 'female', 'African American', 'Warm, approachable, confident and genuine', 'Young Adult'],
  ['Zack', 48, 'male', 'Mediterranean', 'Friendly confident approachable gentleman', 'Professional'],
  ['Brittany', 28, 'female', 'Caucasian', 'warm, approachable, genuine, understated elegance', 'Mom'],
  ['Karim', 42, 'male', 'Middle Eastern', 'Intellectual, thoughtful, well-read', 'Professional'],
  ['Amanda', 32, 'female', 'Caucasian', 'Relaxed, approachable, effortlessly stylish', 'Mom'],
  ['Tunde', 28, 'male', 'African American', 'Creative, artistic, laid-back vibe', 'Young Adult'],
  ['Ji-Yeon', 22, 'female', 'East Asian', 'Friendly, approachable, casual and warm', 'Young Adult'],
  ['Segun', 65, 'male', 'African American', 'Warm, dignified, approachable wisdom', 'Elder'],
  ['Wanjiku', 26, 'female', 'Asian', 'Warm, approachable, genuine person', 'Young Adult'],
  ['Alex', 32, 'male', 'Pacific Islander', 'Friendly, approachable gym enthusiast vibe', 'Young Adult'],
  ['Zeynep', 28, 'female', 'Middle Eastern', 'Elegant, poised, and sophisticated presence', 'Professional'],
  ['Jacob', 35, 'male', 'Caucasian', 'Athletic, straightforward, approachable', 'Professional'],
  ['Gloria', 24, 'female', 'Latina', 'Confident, approachable, warm, and genuine', 'Young Adult'],
  ['Biodun', 28, 'male', 'African American', 'Confident, friendly, approachable professional', 'Young Adult'],
  ['Soo-Jin', 24, 'female', 'East Asian', 'Cheerful, energetic, social media savvy', 'Young Adult'],
  ['Logan', 28, 'male', 'Caucasian', 'Casual, friendly, approachable creative vibe', 'Young Adult'],
  ['Priya', 26, 'female', 'South Asian', 'Warm, approachable, effortlessly genuine', 'Young Adult'],
  ['Ryan', 55, 'male', 'Caucasian', 'Intellectual, composed, thoughtful presence', 'Professional'],
  ['Na-Rae', 22, 'female', 'East Asian', 'Casual, approachable, contemporary urban vibe', 'Young Adult'],
  ['Adaeze', 24, 'female', 'African American', 'Joyful, vibrant, and authentically cheerful', 'Young Adult'],
  ['Leon', 45, 'male', 'European', 'Sophisticated retro vintage gentleman vibes', 'Professional'],
  ['Xiao', 28, 'female', 'East Asian', 'Calm, approachable, understated elegance', 'Professional'],
  ['Miguel', 42, 'male', 'Latino', 'Casual, approachable, friendly outdoor vibe', 'Professional'],
  ['Chinwe', 26, 'female', 'African American', 'Warm, relaxed, and approachable vibe', 'Young Adult'],
  ['Rotimi', 28, 'male', 'African American', 'Relaxed, confident, tropical vacation vibe', 'Young Adult'],
  ['Nathan', 45, 'male', 'Caucasian', 'Contemplative, sophisticated, minimalist aesthetic', 'Professional'],
  ['Ji-Ho', 25, 'male', 'Southeast Asian', 'Laid-back, friendly, casual and approachable', 'Young Adult'],
  ['Jason', 35, 'male', 'Caucasian', 'Laid-back, approachable, casual confidence', 'Casual'],
  ['Sam', 32, 'male', 'Mediterranean', 'Stylish, approachable, modern creative', 'Young Adult'],
  ['Kunle', 45, 'male', 'African American', 'Warm, approachable, thoughtful presence', 'Professional'],
  ['Sung', 22, 'male', 'East Asian', 'Friendly, approachable, casual confidence', 'Young Adult'],
  ['Walid', 45, 'male', 'Middle Eastern', 'Sophisticated, thoughtful, and distinguished', 'Professional'],
  ['Lanre', 25, 'male', 'African American', 'Friendly, approachable, casual warmth', 'Young Adult'],
  ['Finn', 32, 'male', 'European', 'Approachable, modern, thoughtful presence', 'Professional'],
  ['Diego', 26, 'male', 'Latino', 'Friendly, approachable, warm energy', 'Young Adult'],
  ['Chen', 55, 'male', 'East Asian', 'Intellectual, approachable, thoughtful professional', 'Professional'],
  ['Bayo', 28, 'male', 'African American', 'Intelligent, approachable, thoughtful presence', 'Young Adult'],
  ['Chidi', 25, 'male', 'African American', 'Friendly, approachable, warm smile energy', 'Young Adult'],
  ['Kevin', 42, 'male', 'Caucasian', 'Thoughtful, laid-back, creative beard enthusiast', 'Professional'],
  ['Li', 22, 'male', 'East Asian', 'Soft, gentle, modern aesthetic vibes', 'Young Adult'],
  ['Brian', 26, 'male', 'Caucasian', 'friendly approachable genuine smile', 'Young Adult'],
  ['Samir', 28, 'male', 'Middle Eastern', 'Thoughtful, artistic, introspective creative', 'Young Adult'],
  ['Kyle', 45, 'male', 'Caucasian', 'Intellectual, thoughtful, approachable confidence', 'Professional'],
  ['Tao', 26, 'male', 'East Asian', 'Friendly, approachable, casual charm', 'Young Adult'],
  ['Raj', 26, 'male', 'South Asian', 'Confident, approachable, modern casual', 'Young Adult'],
  ['Alejandro', 24, 'male', 'Latino', 'Friendly, approachable, casual confidence', 'Young Adult'],
  ['Uche', 35, 'male', 'African American', 'Confident, approachable, and thoughtful presence', 'Professional'],
  ['Noah', 28, 'male', 'European', 'Friendly, approachable, casual intellectual', 'Young Adult'],
  ['Brett', 28, 'male', 'Caucasian', 'Creative, relaxed, artistic musician vibes', 'Young Adult'],
  ['Marcus', 28, 'male', 'African American', 'Friendly, approachable, warm and confident', 'Young Adult'],
  ['Reed', 42, 'male', 'Mediterranean', 'Confident, approachable, warm elegance', 'Professional'],
  ['Feng', 35, 'male', 'Southeast Asian', 'Approachable, calm, and genuinely friendly', 'Professional'],
  ['Chad', 32, 'male', 'Caucasian', 'Intellectual, thoughtful, creative bookworm', 'Young Adult'],
  ['Cody', 58, 'male', 'Caucasian', 'Warm, approachable, confident professional', 'Professional'],
  ['Elias', 28, 'male', 'Mediterranean or Southern European', 'Relaxed, approachable, creative indie vibe', 'Young Adult'],
  ['Derek', 35, 'male', 'Caucasian', 'Confident, bearded, approachable creative', 'Professional'],
  ['Ying', 24, 'female', 'East Asian', 'Approachable, youthful, warm and friendly', 'Young Adult'],
  ['Devon', 48, 'male', 'African American', 'Intellectual, thoughtful, approachable professional', 'Professional'],
  ['Ricardo', 32, 'male', 'Latin American', 'Confident, approachable, casual streetwear vibe', 'Young Adult'],
  ['Dustin', 32, 'male', 'Caucasian', 'Approachable, friendly, casual confidence', 'Professional'],
  ['Hunter', 24, 'male', 'Caucasian', 'Friendly, approachable, cheerful and warm', 'Young Adult'],
  ['Faris', 32, 'male', 'Middle Eastern', 'Thoughtful, calm, introspective presence', 'Professional'],
  ['Travis', 45, 'male', 'Caucasian', 'Thoughtful, intellectual, approachable presence', 'Professional'],
  ['Liang', 28, 'male', 'East Asian', 'Confident, approachable, modern casual charm', 'Young Adult'],
  ['Vikram', 32, 'male', 'South Asian', 'Friendly, approachable, casual confidence', 'Young Adult'],
  ['Bo', 26, 'male', 'Southeast Asian', 'Artistic, creative, relaxed indie vibe', 'Young Adult'],
  ['Jamal', 42, 'male', 'African American', 'Confident, thoughtful, approachable professional', 'Professional'],
  ['Blake', 28, 'male', 'Caucasian', 'Casual, friendly, approachable guy', 'Young Adult'],
  ['Kayla', 24, 'female', 'Caucasian', 'Artistic, introspective, vintage-inspired aesthetic', 'Young Adult'],
  ['Cole', 45, 'male', 'Mediterranean', 'Thoughtful, vintage-inspired, casually sophisticated', 'Professional'],
  ['Fang', 28, 'female', 'East Asian', 'calm, approachable, naturally elegant presence', 'Professional'],
  ['Eduardo', 42, 'male', 'Latin American', 'Confident, approachable, casual charm', 'Professional'],
  ['Aisha', 26, 'female', 'African American', 'Relaxed, warm, creative home vibe', 'Young Adult'],
  ['Kwame', 28, 'male', 'African American', 'Relaxed tropical vacation confidence', 'Young Adult'],
  ['Colton', 45, 'male', 'Caucasian', 'Calm, introspective, minimalist confidence', 'Professional'],
  ['Jian', 25, 'male', 'Southeast Asian', 'Casual, approachable, friendly vibe', 'Young Adult'],
  ['Ainur', 42, 'female', 'Mediterranean', 'Warm, approachable, and naturally confident', 'Mom'],
  ['Rohan', 48, 'male', 'South Asian', 'Thoughtful, introspective, intellectual presence', 'Professional'],
  ['Ren', 58, 'male', 'East Asian', 'Thoughtful, composed, culturally grounded presence', 'Elder'],
  ['Amber', 62, 'female', 'Asian American', 'Serene, contemplative, spiritually grounded presence', 'Elder'],
  ['Kai', 28, 'male', 'Southeast Asian', 'Friendly, approachable, warm smile', 'Young Adult'],
  ['Ngozi', 28, 'female', 'African', 'Warm, genuine, approachable, and vibrant', 'Young Adult'],
  ['Isabelle', 24, 'female', 'Northern European', 'Fresh, approachable, minimalist aesthetic', 'Young Adult'],
  ['Kofi', 65, 'male', 'African American', 'Wise, contemplative, intellectually grounded', 'Elder'],
  ['Ananya', 24, 'female', 'South Asian', 'Thoughtful, serene, culturally grounded presence', 'Young Adult'],
  ['Charlotte', 26, 'female', 'European', 'Warm, approachable, genuinely friendly presence', 'Young Adult'],
  ['Beatriz', 26, 'female', 'Latina', 'Warm, cheerful, approachable and vibrant', 'Young Adult'],
  ['Fatima', 48, 'female', 'Middle Eastern', 'Serene, dignified, contemplative presence', 'Mom'],
  ['Niklas', 48, 'male', 'Northern European', 'Thoughtful, composed, intellectually grounded', 'Professional'],
  ['Chidinma', 26, 'female', 'African American', 'Confident, poised, professional yet approachable', 'Young Adult'],
  ['Dean', 55, 'male', 'Mediterranean', 'Confident, approachable, seasoned professional', 'Professional'],
  ['Fatima', 28, 'female', 'African', 'Vibrant, confident, and approachable', 'Young Adult'],
  ['Lan', 28, 'female', 'East Asian', 'Serene, minimalist, effortlessly elegant', 'Young Adult'],
  ['Xue', 32, 'female', 'East Asian', 'Warm, approachable, naturally elegant', 'Mom'],
  ['Min', 28, 'female', 'Southeast Asian', 'Warm, approachable, friendly and genuine', 'Young Adult'],
  ['Nkechi', 42, 'female', 'African American', 'Confident, poised, and professionally composed', 'Professional'],
  ['Amelie', 35, 'female', 'European', 'Creative, approachable, artistic spirit', 'Mom'],
  ['Lupita', 32, 'female', 'Latina', 'Warm, approachable, genuine homebody energy', 'Mom'],
  ['Rosa', 32, 'female', 'Latina', 'Warm, approachable, and naturally confident', 'Mom'],
  ['Blessing', 35, 'female', 'African American', 'warm, confident, approachable professional presence', 'Professional'],
  ['Jing', 28, 'female', 'East Asian', 'Warm, approachable, naturally radiant', 'Young Adult'],
  ['Chelsea', 42, 'female', 'Caucasian', 'Warm, approachable, genuine, friendly presence', 'Mom'],
  ['Melissa', 62, 'female', 'Caucasian', 'Warm, joyful, vibrant, and approachable', 'Elder'],
  ['Tiffany', 68, 'female', 'Caucasian', 'Warm, gentle, gracefully aging presence', 'Elder'],
  ['Folake', 62, 'female', 'African American', 'Dignified, warm, and culturally proud', 'Elder'],
  ['Divya', 72, 'female', 'Indian', 'Wise, serene, gracefully aged presence', 'Elder'],
  ['Courtney', 62, 'female', 'Caucasian', 'Elegant, refined, gracefully poised sophistication', 'Elder'],
  ['Carmen', 68, 'female', 'Latin American', 'Warm, cheerful, and authentically traditional', 'Elder'],
  ['Yewande', 62, 'female', 'African American', 'Warm, joyful, approachable, genuine spirit', 'Elder'],
  ['Wei', 72, 'female', 'East Asian', 'Serene, dignified, thoughtful presence', 'Elder'],
  ['Heather', 75, 'female', 'Caucasian', 'Warm, cheerful, grandmother-like presence', 'Elder'],
  ['Shannon', 28, 'female', 'Caucasian', 'friendly, approachable, warm and genuine', 'Young Adult'],
  ['Jake', 48, 'male', 'Hispanic', 'Contemplative and serious demeanor', 'Professional'],
  ['Ryu', 35, 'male', 'Southeast Asian', 'Friendly, approachable, warm smile', 'Casual'],
];

export const ACTORS: ActorMeta[] = RAW.map((r, i) => ({
  id: i + 1,
  name: r[0],
  age: r[1],
  gender: r[2],
  nationality: r[3],
  style: r[4],
  type: r[5],
}));
