#!/usr/bin/env tsx
// Copyright 2026 agent-media contributors. Apache-2.0 license.

/**
 * Generates supabase/functions/_shared/schema.generated.ts
 *
 * Supabase edge functions run in Deno and cannot resolve Turborepo
 * workspace packages. This script copies the const arrays from
 * video.ts into a plain Deno-compatible file.
 *
 * The generated file is checked into git (Option A from spec §5.1).
 * CI verifies it matches by re-running this script and diffing.
 */

import {
  DURATIONS,
  TONES,
  MUSIC_GENRES,
  SUBTITLE_STYLES,
  ASPECT_RATIOS,
  SCENE_TYPES,
  TEMPLATES,
  VOICES,
  TTS_PROVIDERS,
  REVIEW_ANGLES,
  PIP_POSITIONS,
  PIP_SIZES,
  PIP_ANIMATIONS,
  PIP_FRAME_STYLES,
  COMPOSITION_MODES,
  BROLL_MODELS,
  CREDITS_PER_SECOND,
  SCRIPT_GENERATION_CREDIT_SURCHARGE,
} from '../src/video.js';

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../../../supabase/functions/_shared/schema.generated.ts');

function toArrayLiteral(name: string, values: readonly (string | number)[]): string {
  const formatted = values.map((v) => (typeof v === 'string' ? `"${v}"` : String(v)));
  if (formatted.join(', ').length < 80) {
    return `export const ${name} = [${formatted.join(', ')}] as const;`;
  }
  return `export const ${name} = [\n  ${formatted.join(',\n  ')},\n] as const;`;
}

const output = `// AUTO-GENERATED by packages/schema/scripts/generate-edge-schema.ts
// DO NOT EDIT. Source of truth: packages/schema/src/video.ts
// Re-generate: pnpm --filter @agent-media/schema generate:edge-schema

${toArrayLiteral('DURATIONS', DURATIONS)}
${toArrayLiteral('TONES', TONES)}
${toArrayLiteral('MUSIC_GENRES', MUSIC_GENRES)}
${toArrayLiteral('SUBTITLE_STYLES', SUBTITLE_STYLES)}
${toArrayLiteral('ASPECT_RATIOS', ASPECT_RATIOS)}
${toArrayLiteral('SCENE_TYPES', SCENE_TYPES)}
${toArrayLiteral('TEMPLATES', TEMPLATES)}
${toArrayLiteral('VOICES', VOICES)}
${toArrayLiteral('TTS_PROVIDERS', TTS_PROVIDERS)}
${toArrayLiteral('REVIEW_ANGLES', REVIEW_ANGLES)}
${toArrayLiteral('PIP_POSITIONS', PIP_POSITIONS)}
${toArrayLiteral('PIP_SIZES', PIP_SIZES)}
${toArrayLiteral('PIP_ANIMATIONS', PIP_ANIMATIONS)}
${toArrayLiteral('PIP_FRAME_STYLES', PIP_FRAME_STYLES)}
${toArrayLiteral('COMPOSITION_MODES', COMPOSITION_MODES)}
${toArrayLiteral('BROLL_MODELS', BROLL_MODELS)}

export const CREDITS_PER_SECOND = ${CREDITS_PER_SECOND};
export const SCRIPT_GENERATION_CREDIT_SURCHARGE = ${SCRIPT_GENERATION_CREDIT_SURCHARGE};
`;

writeFileSync(outputPath, output, 'utf-8');
console.log(`Generated: ${outputPath}`);
