-- Migration: register the 3 character-video pipeline models so
-- generation_jobs.model_slug FK to public.models(slug) resolves.
--
-- The api-v2 routes already insert rows with these slugs:
--   character-sheet      → /v1/character/sheet-generate
--   character-storyboard → /v1/character/storyboard-generate
--   character-video      → /v1/generate/character_video
--
-- Without this migration every insert fails the FK and the user sees
-- "Failed to create job".
--
-- These rows are routing/labelling only — pricing comes from credit_cost
-- on the job row itself, not model_pricing. We mark them is_active=false
-- so the check_pricing_coverage() trigger doesn't require model_pricing
-- rows. The FK from generation_jobs.model_slug doesn't care about is_active.

INSERT INTO public.models (
  slug,
  display_name,
  description,
  media_type,
  provider_slug,
  provider_model_id,
  supports_text_to_video,
  supports_image_to_video,
  supports_text_to_image,
  max_duration_seconds,
  max_resolution,
  is_active,
  default_duration,
  allowed_durations,
  min_plan_tier
) VALUES
  (
    'character-sheet',
    'Character Sheet (gpt-image-2)',
    'Multi-angle character reference sheet generated from a short description (and optional reference image). Used as Step 1 of the character_video pipeline.',
    'image',
    'evolink',
    'gpt-image-2',
    false, false, true,
    NULL, '2K', false,
    NULL, NULL, 'free'
  ),
  (
    'character-storyboard',
    'Character Storyboard (gpt-image-2)',
    'Numbered-panel storyboard sheet that uses the character sheet as a reference image so each panel stays on-character. Step 2 of the character_video pipeline.',
    'image',
    'evolink',
    'gpt-image-2',
    false, false, true,
    NULL, '2K', false,
    NULL, NULL, 'free'
  ),
  (
    'character-video',
    'Character Video (Seedance 2.0)',
    'Final 5–10s character video generated by Seedance 2.0 from the character sheet + storyboard + a short action prompt. Step 3 of the character_video pipeline.',
    'video',
    'evolink',
    'seedance-2.0-image-to-video',
    false, true, false,
    10, '1080p', false,
    10, '[5, 10]'::jsonb, 'free'
  )
ON CONFLICT (slug) DO NOTHING;
